### ISSUE TITLE
Use better atlas packing algorithm

### ISSUE THREAD

**Issue by WeAthFoLD** [WeAthFoLD/MetaSprite#3]
There are (much) better packing algorithms other than shelf packing, such as skyline, subdividing etc. We can achieve higher space efficiency by optimizing atlas packing algorithm.

**Comment by dryn27** [comment]
Hey! I love your asset. It's really awesome :D 
I was wondering... is there a way to not optimize the atlas? I'd like to have every frame on aseprite imported as it is, with no triming if posible.
Thank you for this awesome asset that you are sharing for free. It is soooo incredible ^^

**Comment by WeAthFoLD** [comment]
> @dryn27 

Hi, glad you liked my work! Using full atlas without cropping sounds like useful in some scenarios, and can be implemented trivially in MetaSprite (just needed to skip the bounds recalculation section). What about adding an option in import settings to tweak it?

**Comment by dryn27** [comment]
Yes! Please! That would be amazing ^^

**Comment by WeAthFoLD** [comment]
Implemented in ffb9a7e9c63a7aeecd71fd2235f9a1dc8804e7c3. Sorry for taking so long I finally find some time to take a break =w=

**Comment by dryn27** [comment]
Thank you! >o<
