### ISSUE TITLE
Creating animations for every content layer

### ISSUE THREAD

**Issue by net8floz** [WeAthFoLD/MetaSprite#6]
Would it be possible to get some advice on how to extend the functionality of this so that I can create clips and atlases for every layer per tag in my .ase file?

**Comment by WeAthFoLD** [comment]
You mean that for each clip and tag, generate a unique animation clip for it? That is certainly doable, but you need to write customized import routine for that. You can start from [ASEImporter.Import][aseimporter], which controls the whole importing process.

Current process can be concluded as:

1. Generate atlas for all contents
2. Generate animation clips from tags
3. Generate animator controller from clips
4. Invoke metadata processors for extended functionality

And for your need, the whole process can be modified to:

1. For each layer, generate the layer's atlas
2. Generate animation clips for each (layer, tag) combination
3. Generate animator controller from clips
4. Invoke metadata processors if you want

I'd say the work is mainly in step 1 and 2, later stages remain largely the same.

[aseimporter]: https://github.com/WeAthFoLD/MetaSprite/blob/2444617f296de6335628cb726148f73129694a3d/Assets/Plugins/MetaSprite/Editor/ASEImporter.cs#L91

**Comment by WeAthFoLD** [comment]
I'll close the issue for now as there are no new updates. Please fire a new issue if there's anything else you wanna ask.
