### ISSUE TITLE
Pivot is created by location in aesprite ?

### ISSUE THREAD

**Issue by gotenxds** [WeAthFoLD/MetaSprite#8]
So, I have multiple tags for my walk cycle, like up, down, left and so on, they are not in the same place in the aesprite canvas, I think this results in this:

![issue](https://user-images.githubusercontent.com/3519520/47957489-5275ce80-dfbf-11e8-857b-babf81e473dc.gif)

**Comment by WeAthFoLD** [comment]
Mind posting your import settings? also are you using `@pivot` layers in your ase file?

Also I didn't think I fully understood your problem, would appreciate a little more detail :-)
